### ISSUE TITLE
Compile/extract command doesn't work on Windows

### ISSUE THREAD

**Issue by kirillku** [lingui/js-lingui#110]
Getting this error when running command to add a new locale:
```bash
$ lingui add-locale cs
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\<projectDir>\locale\cs\messages.json'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at Object.write (C:\<projectDir>\node_modules\lingui-cli\dist\api\formats\lingui.js:60:20)
    at Object.addLocale (C:\<projectDir>\node_modules\lingui-cli\dist\api\formats\lingui.js:162:14)
    at C:\<projectDir>\node_modules\lingui-cli\dist\lingui-add-locale.js:29:36
    at Array.map (<anonymous>)
    at command (C:\<projectDir>\node_modules\lingui-cli\dist\lingui-add-locale.js:28:25)
    at Object.<anonymous> (C:\<projectDir>\node_modules\lingui-cli\dist\lingui-add-locale.js:68:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
error Command failed with exit code 1.
```

lingui-cli 1.3.7
windows 10 (tried both from command prompt and git bash)

**Comment by tricoder42** [comment]
@kirillku Thank you! It should be fixed in latest `lingui-cli@1.3.9`, could you please confirm?

**Comment by kirillku** [comment]
Just checked with new version, having the same issue
```bash
$ yarn global list
yarn global v1.2.1
info "lingui-cli@1.3.9" has binaries:
   - lingui
Done in 1.46s.

$ lingui add-locale cs
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\<projectDir>\locale\cs\messages.json'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at Object.write (C:\<yarnGlobalDir>\node_modules\lingui-cli\dist\api\formats\lingui.js:60:20)
    at Object.write (C:\<yarnGlobalDir>\node_modules\lingui-cli\dist\api\formats\minimal.js:43:27)
    at Object.addLocale (C:\<yarnGlobalDir>\node_modules\lingui-cli\dist\api\formats\lingui.js:162:14)
    at C:\<yarnGlobalDir>\node_modules\lingui-cli\dist\lingui-add-locale.js:29:36
    at Array.map (<anonymous>)
    at command (C:\<yarnGlobalDir>\node_modules\lingui-cli\dist\lingui-add-locale.js:28:25)
    at Object.<anonymous> (C:\<yarnGlobalDir>\node_modules\lingui-cli\dist\lingui-add-locale.js:68:3)
    at Module._compile (module.js:624:30)
```

**Comment by tricoder42** [comment]
> 'C:\<projectDir>\locale\cs\messages.json'

Seems like you're using `<projectDir>` instead of `<rootDir>`. Take a look at [reference documentation](https://lingui.github.io/js-lingui/ref/lingui-conf.html) for more info.

Sorry I didn't notice for the first time. Another user said he has a problem with Windows as well and I found a place where file path wasn't created in platform agnostic way. Your problem seems to be different.

**Comment by kirillku** [comment]
Ah, sorry, it's just placeholder, i replaced the actual path in the output with wrong string, in my `package.json` i'm using `<rootDir>`.

**Comment by tricoder42** [comment]
Ok, I'll take a look at test it on my windows machine.

In the meantime, please create `C:\<rootDir>\locale\cs\` manually.

**Comment by RogerGodefroy** [comment]
I also note an issue when extracting on windows.

The getLocales function in ```api/formats/lingui.js``` receives the sources as:

```[ 'locale/en/messages.json' ]```

The regex wouldn't match to 'en', which would result in no match.

This gives me the following error on windows:

```No locales defined!```

**Comment by shye0000** [comment]
Same issues here when extracting and compiling on windows.

`No locales defined!`

**Comment by shye0000** [comment]
Any news about this issue?

**Comment by tricoder42** [comment]
@shye0000 I'll take a look over the weekend.

In the meantime, please create language directories manually (e.g: `locale/en`).

**Comment by tricoder42** [comment]
@RogerGodefroy @shye0000 It should be fixed in **lingui-cli@1.3.10**, could you please confirm?

**Comment by shye0000** [comment]
@tricoder42 I didn't try `add-locale` on windows, but it is still not working when `lingui extract` and `lingui compile` on windows.
Same error like before: `No locales defined!`

**Comment by shye0000** [comment]
@tricoder42 the `add-locale` is working on windows! Je just tested it. Thank you.

**Comment by tricoder42** [comment]
@shye0000 So `add-locale` works, but `extract` and `compile` still fails, right?

**Comment by shye0000** [comment]
@tricoder42 yes, exactly

**Comment by ingro** [comment]
Same problem here, let me know if there is something I could do to debug the issue!

**Comment by tricoder42** [comment]
@ingro I have to find Windows machine to test it anyway, but could you please copy-paste me the error? It's the same as above, file does no exist?

**Comment by ingro** [comment]
Same error as above, `No locales defined!`.

Trying to run the script on bash for windows it runs even if not successfull, I got some strange babel-related issue, might be because i'm using Create-React-App.

**Comment by tricoder42** [comment]
@ingro Yes, CRA is problematic, because it hardcodes babel config into webpack confing. The easiest fix is to create `.babelrc` with `react-app` preset only. Anyway, I'm gonna test it on Windows tonight.

**Comment by ingro** [comment]
Thanks for the suggestion, I was able to run the `extract` command without errors!

**Comment by tricoder42** [comment]
@ingro Awesome! Glad it works 👍 

@kirillku @RogerGodefroy @shye0000 Do you also use create-react-app?

**Comment by tricoder42** [comment]
@kirillku @RogerGodefroy @shye0000 I managed to test all CLI commands in Windows environment and probably fixed the bug. Could you please test latest version of lingui-cli, **1.3.12**? I'm just a bit uncertain, because I mostly reverted all changes to original state.

**Comment by RogerGodefroy** [comment]
I'll give it a try tomorrow. I'll let you know...

**Comment by tricoder42** [comment]
@XSlemX Uff, I really don't understand how I missed that. Using lingui-cli for 6 months and never saw this error :/

Dependencies are fixed in **lingui-cli@1.3.13**, thank you for debugging this!

**Comment by kirillku** [comment]
@tricoder42 checked, everything works now

**Comment by ingro** [comment]
Same here, good job @tricoder42 !
