### ISSUE TITLE
Custom TypescriptLoader for cosmic config breaks import/require module resolution

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1295]
**Describe the bug**
Create typescript config file `lingui.config.ts` with any import or require
```typescript
import { ALL_LANGUAGES_ARRAY, DEFAULT_LANGUAGE } from './languages';

module.exports = {
  locales: ALL_LANGUAGES_ARRAY.map((l) => l.key),
  sourceLocale: DEFAULT_LANGUAGE,
  catalogs: [{
    path: '<rootDir>/translates/{locale}',
    include: ['<rootDir>/src'],
  }],
  format: 'po',
};
```

Run the extractor. And you will get an error pointing that module not found 

If you rename file to plain js it works. 
If you put a `console.log(__dirname)` in both files you will see that js files executed from it's original place, where ts file executed from insides of lingui package. 

That's caused by custom TypescriptLoader for cosmiconfig defined here 
https://github.com/lingui/js-lingui/blob/da070ba294435484fde10d82ecb895d2410ec1b7/packages/conf/src/index.ts#L580-L587

Which is basically just eval the code in place. 
 
**Rationality** 
Although the configuration is usually very simple, it's not the case where you have a monorepo with different frameworks and tools. Writing and maintaining list of languages in every app in such monorepo could be cumbersome and easy to forget to add language in one of places. That's why we use one monorepo-wide file with all languages definitions written in TS. 

**Proposed solution:**
Get rid of this custom, "fast" and actually, broken loader in favour of standart one. 

**Additional context**

- jsLingui version ``3.14.0``

**Comment by semoal** [comment]
This should be fixed on https://github.com/lingui/js-lingui/pull/1247, 3.15.0

Give it a try, :)

**Comment by thekip** [comment]
It still an issue. The mentioned PR updated a package which not used in the code. Current codebase still has: 

```ts
    loaders: {
      ".ts": TypeScriptLoader,
    },

   //....
/** Typescript loader using just typescript API and eval(), instead of using ts-node/register which is slower */
function TypeScriptLoader(filePath: string) {
  const tsc = require("typescript")
  const fileContent = fs.readFileSync(filePath, "utf-8")
  const { outputText } = tsc.transpileModule(fileContent, { compilerOptions: { module: tsc.ModuleKind.CommonJS }});
  const configFileParsed = eval(outputText)
  return configFileParsed
}
```

Which is not working as it should
