### ISSUE TITLE
Extraction not working correctly after updating to 3.15

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#1300]
**Describe the bug**
After updating to 3.15, `lingui extract --clean --overwrite` is giving unexpected results.

**To Reproduce**

I have a simple component:

`<Trans id="form.friend.name.label">My Friend&apos;s Name</Trans>`

With 3.14, `messages.po` for the source language (English) looks like:

Source: `form.friend.name.label` 
Translation: `My Friend's Name`

But with 3.15:

Source: `form.friend.name.label` 
Translation: `form.friend.name.label` 

**Expected behavior**

I expect the behavior in 3.15 to be the same as 3.14.

- Babel version ``npm list @babel/core``

```
─┬ @babel/eslint-parser@7.19.1
│ └─┬ @babel/core@7.20.2
│   └─┬ @babel/helper-compilation-targets@7.20.0
│     └── @babel/core@7.20.2 deduped
├─┬ @lingui/cli@3.15.0
│ ├── @babel/core@7.20.2 deduped
│ └─┬ @babel/plugin-syntax-jsx@7.18.6
│   └── @babel/core@7.20.2 deduped
├─┬ eslint-plugin-flowtype@8.0.3
│ ├─┬ @babel/plugin-syntax-flow@7.18.6
│ │ └── @babel/core@7.20.2 deduped
│ └─┬ @babel/plugin-transform-react-jsx@7.19.0
│   └── @babel/core@7.20.2 deduped
└─┬ react-scripts@5.0.1
  ├── @babel/core@7.20.2 deduped
  ├─┬ @svgr/webpack@5.5.0
  │ ├── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-transform-react-constant-elements@7.20.2
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/preset-env@7.20.2
  │ │ ├── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-async-generator-functions@7.20.1
  │ │ │ ├── @babel/core@7.20.2 deduped
  │ │ │ └─┬ @babel/helper-remap-async-to-generator@7.18.9
  │ │ │   └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-class-static-block@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-dynamic-import@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-export-namespace-from@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-json-strings@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-logical-assignment-operators@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-object-rest-spread@7.20.2
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-optional-catch-binding@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-private-property-in-object@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-proposal-unicode-property-regex@7.18.6
  │ │ │ ├── @babel/core@7.20.2 deduped
  │ │ │ └─┬ @babel/helper-create-regexp-features-plugin@7.19.0
  │ │ │   └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-async-generators@7.8.4
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-class-properties@7.12.13
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-class-static-block@7.14.5
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-dynamic-import@7.8.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-export-namespace-from@7.8.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-import-assertions@7.20.0
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-json-strings@7.8.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-logical-assignment-operators@7.10.4
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-nullish-coalescing-operator@7.8.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-numeric-separator@7.10.4
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-object-rest-spread@7.8.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-optional-catch-binding@7.8.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-optional-chaining@7.8.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-private-property-in-object@7.14.5
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-syntax-top-level-await@7.14.5
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-arrow-functions@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-async-to-generator@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-block-scoped-functions@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-block-scoping@7.20.2
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-classes@7.20.2
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-computed-properties@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-destructuring@7.20.2
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-dotall-regex@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-duplicate-keys@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-exponentiation-operator@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-for-of@7.18.8
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-function-name@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-literals@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-member-expression-literals@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-modules-amd@7.19.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-modules-commonjs@7.19.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-modules-systemjs@7.19.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-modules-umd@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-named-capturing-groups-regex@7.19.1
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-new-target@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-object-super@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-parameters@7.20.3
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-property-literals@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-regenerator@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-reserved-words@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-shorthand-properties@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-spread@7.19.0
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-sticky-regex@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-template-literals@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-typeof-symbol@7.18.9
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-unicode-escapes@7.18.10
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-unicode-regex@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/preset-modules@0.1.5
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ ├─┬ babel-plugin-polyfill-corejs2@0.3.3
  │ │ │ ├── @babel/core@7.20.2 deduped
  │ │ │ └─┬ @babel/helper-define-polyfill-provider@0.3.3
  │ │ │   └── @babel/core@7.20.2 deduped
  │ │ ├─┬ babel-plugin-polyfill-corejs3@0.6.0
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ └─┬ babel-plugin-polyfill-regenerator@0.4.1
  │ │   └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/preset-react@7.18.6
  │ │ ├── @babel/core@7.20.2 deduped
  │ │ ├─┬ @babel/plugin-transform-react-jsx-development@7.18.6
  │ │ │ └── @babel/core@7.20.2 deduped
  │ │ └─┬ @babel/plugin-transform-react-pure-annotations@7.18.6
  │ │   └── @babel/core@7.20.2 deduped
  │ └─┬ @svgr/plugin-jsx@5.5.0
  │   └── @babel/core@7.20.2 deduped
  ├─┬ babel-jest@27.5.1
  │ ├── @babel/core@7.20.2 deduped
  │ ├─┬ @jest/transform@27.5.1
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ babel-plugin-istanbul@6.1.1
  │ │ └─┬ istanbul-lib-instrument@5.2.1
  │ │   └── @babel/core@7.20.2 deduped
  │ └─┬ babel-preset-jest@27.5.1
  │   ├── @babel/core@7.20.2 deduped
  │   └─┬ babel-preset-current-node-syntax@1.0.1
  │     ├── @babel/core@7.20.2 deduped
  │     ├─┬ @babel/plugin-syntax-bigint@7.8.3
  │     │ └── @babel/core@7.20.2 deduped
  │     └─┬ @babel/plugin-syntax-import-meta@7.10.4
  │       └── @babel/core@7.20.2 deduped
  ├─┬ babel-loader@8.3.0
  │ └── @babel/core@7.20.2 deduped
  ├─┬ babel-plugin-named-asset-import@0.3.8
  │ └── @babel/core@7.20.2 deduped
  ├─┬ babel-preset-react-app@10.0.1
  │ ├── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-proposal-class-properties@7.18.6
  │ │ ├── @babel/core@7.20.2 deduped
  │ │ └─┬ @babel/helper-create-class-features-plugin@7.20.2
  │ │   └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-proposal-decorators@7.20.2
  │ │ ├── @babel/core@7.20.2 deduped
  │ │ └─┬ @babel/plugin-syntax-decorators@7.19.0
  │ │   └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-proposal-nullish-coalescing-operator@7.18.6
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-proposal-numeric-separator@7.18.6
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-proposal-optional-chaining@7.18.9
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-proposal-private-methods@7.18.6
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-transform-flow-strip-types@7.19.0
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-transform-react-display-name@7.18.6
  │ │ └── @babel/core@7.20.2 deduped
  │ ├─┬ @babel/plugin-transform-runtime@7.19.6
  │ │ └── @babel/core@7.20.2 deduped
  │ └─┬ @babel/preset-typescript@7.18.6
  │   ├── @babel/core@7.20.2 deduped
  │   └─┬ @babel/plugin-transform-typescript@7.20.2
  │     ├── @babel/core@7.20.2 deduped
  │     └─┬ @babel/plugin-syntax-typescript@7.20.0
  │       └── @babel/core@7.20.2 deduped
  ├─┬ eslint-config-react-app@7.0.1
  │ └── @babel/core@7.20.2 deduped
  ├─┬ jest@27.5.1
  │ └─┬ @jest/core@27.5.1
  │   ├─┬ jest-config@27.5.1
  │   │ └── @babel/core@7.20.2 deduped
  │   └─┬ jest-snapshot@27.5.1
  │     └── @babel/core@7.20.2 deduped
  └─┬ workbox-webpack-plugin@6.5.4
    └─┬ workbox-build@6.5.4
      ├── @babel/core@7.20.2 deduped
      └─┬ @rollup/plugin-babel@5.3.1
        └── @babel/core@7.20.2 deduped
```

- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
I'm using Create React App with React 18 for an Ionic 6 app.

**Comment by evertbouw** [comment]
I'm using Vite instead of CRA but I was using
```json
  "extractBabelOptions": {
    "presets": ["react-app"]
  }
```
Replacing that with
```json
"extractBabelOptions": {
  "presets": ["@babel/preset-typescript"]
}
```
fixed this problem for me. In case this helps anyone 🤷

**Comment by ptmkenny** [comment]
I didn't have `extractBabelOptions` in my `lingui.config.ts`, but setting that as described by @evertbouw did not solve the problem for me (both `react-app` and `@babel/preset-typescript` didn't work).

Here is my **lingui.config.ts**:

```
const config = {
  locales: ['en', 'ja'],
  sourceLocale: 'en',
  catalogs: [
    {
      path: 'src/locales/{locale}/messages',
      include: ['src'],
    },
  ],
  compileNamespace: 'ts',
  format: 'po',
};

export default config;

```

**Comment by ptmkenny** [comment]
Looks like this was broken by this merge request: https://github.com/lingui/js-lingui/commit/90be1719becc4710c910ea16928b7ce41ef9ab19

Perhaps this new feature could be rolled back until the issue is fixed?

**Comment by Martin005** [comment]
@ptmkenny The mentioned merge request https://github.com/lingui/js-lingui/commit/90be1719becc4710c910ea16928b7ce41ef9ab19 was actually merged on December 8, but the version 3.15.0 was released on November 7, so this is unrelated

**Comment by thekip** [comment]
@Martin005  i already looking into issue in 3.15
