### ISSUE TITLE
Lingui Extract cause allocation failure

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1405]
Moved from here https://github.com/lingui/swc-plugin/issues/14

```
[biwano@localhost app]$ npx lingui extract

<--- Last few GCs --->

[181958:0x558f89923640]    67708 ms: Scavenge (reduce) 2042.5 (2081.9) -> 2042.0 (2082.2) MB, 8.5 / 0.0 ms  (average mu = 0.298, current mu = 0.315) allocation failure 
[181958:0x558f89923640]    67727 ms: Scavenge (reduce) 2042.8 (2082.2) -> 2042.2 (2082.2) MB, 11.5 / 0.0 ms  (average mu = 0.298, current mu = 0.315) allocation failure 
[181958:0x558f89923640]    67745 ms: Scavenge (reduce) 2043.4 (2082.5) -> 2042.8 (2082.8) MB, 7.6 / 0.0 ms  (average mu = 0.298, current mu = 0.315) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x558f859ead94 node::Abort() [/usr/bin/node]
 2: 0x558f858a30b6 node::OnFatalError(char const*, char const*) [/usr/bin/node]
 3: 0x558f85bd7b5a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0x558f85bd7de6 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0x558f85d77eb9  [/usr/bin/node]
 6: 0x558f85d77ffc  [/usr/bin/node]
 7: 0x558f85d90535 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0x558f85d90df4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0x558f85d93e34 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0x558f85d93ec9 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
11: 0x558f85d5de3f v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
12: 0x558f8609f200 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
13: 0x558f86475959  [/usr/bin/node]
```

Steps to reproduce:
```
git clone https://github.com/KlimaDAO/klimadao --branch 922_swc_plugin_for_lingui --depth 1
cd klimadao
npm install
npm run build-lib
cd app
npx lingui extract
```

**Comment by FabianMeul** [comment]
I'm also experiencing this issue.

Node: 18.14.0
@lingui/cli: 3.17.0
@babel/core@7.20.12

**Comment by FabianMeul** [comment]
Thanks for following this up so quickly;


More context after debugging on my end;
The extraction process works fine when using `3.16.1`.

**Comment by thekip** [comment]
Should be fixed in `3.17.1`

**Comment by h2dthien** [comment]
Hey folks, anyone still see the failure after 3.17.1? It still happens on my setup..

**Comment by h2dthien** [comment]
Actually thanks @FabianMeul 3.16.1 works like a charm. It's done almost instantly, while 3.17.1 still hang and OOM after about 1 minute

**Comment by thekip** [comment]
@h2dthien what format for lingui config you use? If typescript - that would be a reason. Renaming to js would fix it currently

**Comment by h2dthien** [comment]
@thekip thanks! Trying it now

**Comment by h2dthien** [comment]
Hey @thekip and all: I confirm that it works perfectly after changing the config from .ts to .js!

**Comment by thekip** [comment]
The proper fix will land in v4. This requiring fundamental changes, unfortunately.

**Comment by taozhou-glean** [comment]
well, switching from `.ts` to `.js` fixed the OOM issue for me, but I am getting `Maximum call stack size exceeded` while it works just fine if I pass that file to extract

**Comment by taozhou-glean** [comment]
> well, switching from `.ts` to `.js` fixed the OOM issue for me, but I am getting `Maximum call stack size exceeded` while it works just fine if I pass that file to extract

looking at the source code, it should do exactly the same with or without the `paths` arg, and the error is from babel core, so it's likely some code pattern in our own codebase causing the trouble
