### ISSUE TITLE
js-lingui does not work with @babel/core 7.0.0

### ISSUE THREAD

**Issue by elios264** [lingui/js-lingui#163]
I'm trying to integrate js-lingui with my project but it keeps failing, 
some of the errors I get are:

ERROR in ./src/client/appLoader.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions.

or 

@babel\plugin-transform-spread\lib\index.js:9
  var loose = options.loose;
                      ^

TypeError: Cannot read property 'loose' of undefined
    at _default (...node_modules\@babel\plugin-transform-spread\lib\index.js:9:23)

are you planning to update to new the new babel?

**Comment by tricoder42** [comment]
Hey @elios264,
I'm using new (7.x) babel in both examples (see this [`.babelrc`](https://github.com/lingui/js-lingui/blob/master/examples/webpack-react/.babelrc)).

What plugins you're using and how your `.babelrc` looks like?

**Comment by lexkrstn** [comment]
I'm getting the first error too.
Just temporary fixed it by not using the preset and placing its plugins into babel config instead.
`@babel/core 7.0.0-beta.40`

**Comment by elios264** [comment]
Hi @tricoder42, 

This is my .babelrc file

```
{
  "presets": [
    "@babel/preset-react",
    "@lingui/babel-preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-decorators",
    "@babel/plugin-transform-spread",
    "@babel/plugin-proposal-object-rest-spread",
    ["@babel/plugin-proposal-class-properties", { "loose": true } ],
    ["import", { "libraryName": "antd", "libraryDirectory": "es" }]
  ],
  "env": {
    "production": {
      "presets": [
        ["@babel/preset-env", { "useESModules": true, "debug": true, "loose": true, "useBuiltIns": false, "modules": false, "targets": { "browsers": ["> 1%"] } }]
      ]
    },
    "development": {
      "presets": [
        ["@babel/preset-env", { "useESModules": true, "debug": true, "loose": true, "useBuiltIns": false, "modules": false, "targets": { "chrome": 64 } }]
      ]
    }
  }
}

```
As stated in the [docs](https://lingui.github.io/js-lingui/tutorials/react.html#installing-jslingui) I added the preset,  but I see in the example you [provided me](https://github.com/lingui/js-lingui/blob/master/examples/webpack-react/.babelrc) you are not using the preset and instead the plugins directly, I also just tried that but is not working either,

The error  i keep getting when running  `lingui extract` is:

```
Extracting messages from source files…
C:\Users\elios\elios' files\Projects\X-Evolvers\PRGNRS\customair\node_modules\@babel\plugin-transform-spread\lib\index.js:9
  var loose = options.loose;
                      ^

TypeError: Cannot read property 'loose' of undefined
    at _default (C:\Users\elios\elios' files\Projects\X-Evolvers\PRGNRS\customair\node_modules\@babel\plugin-transform-spread\lib\index.js:9:23)
    at Function.memoisePluginContainer (C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
    at Function.normalisePlugin (C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
    at C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\elios\AppData\Roaming\npm\node_modules\babel-core\lib\transformation\file\index.js:135:24)
```
this is my package.json:

```
{
  "name": "customair",
  "version": "1.0.0",
  "description": "Customair",
  "scripts": {
    "postinstall": "patch-package",
    "start": "cross-env NODE_ENV=development node ./server.js",
    "start:prod": "cross-env NODE_ENV=production node ./server.js",
    "start:lint": "eslint ./src ./cloud --color",
    "build": "cross-env NODE_ENV=production webpack",
    "deploy": "echo \"Error: no deploy specified\" && exit 1",
    "prestart": "npm run start:lint",
    "prebuild": "npm run start:lint"
  },
  "private": true,
  "author": "elios264",
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.40",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.40",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.40",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0-beta.40",
    "@babel/plugin-transform-spread": "^7.0.0-beta.40",
    "@babel/polyfill": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-react": "^7.0.0-beta.40",
    "@lingui/babel-plugin-transform-js": "^2.0.2",
    "@lingui/babel-plugin-transform-react": "^2.0.2",
    "@lingui/babel-preset-react": "^2.0.2",
    "babel-eslint": "^8.2.1",
    "babel-loader": "^8.0.0-beta.0",
    "babel-plugin-import": "^1.6.5",
    "babel-plugin-lingui-extract-messages": "^1.1.12",
    "clean-webpack-plugin": "^0.1.18",
    "copy-webpack-plugin": "^4.4.1",
    "cross-env": "^5.1.3",
    "css-loader": "^0.28.9",
    "eslint": "^4.18.0",
    "eslint-import-resolver-webpack": "^0.8.4",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-react": "^7.6.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.6",
    "html-webpack-plugin": "^2.30.1",
    "less": "^2.7.3",
    "less-loader": "^4.0.5",
    "patch-package": "^5.1.1",
    "react-hot-loader": "^3.1.3",
    "style-loader": "^0.20.2",
    "uglifyjs-webpack-plugin": "^1.2.0",
    "url-loader": "^0.6.2",
    "webpack": "^3.11.0",
    "webpack-dev-middleware": "^2.0.5",
    "webpack-hot-middleware": "^2.21.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome": "^1.1.3",
    "@fortawesome/fontawesome-free-brands": "^5.0.6",
    "@fortawesome/fontawesome-free-regular": "^5.0.6",
    "@fortawesome/fontawesome-free-solid": "^5.0.6",
    "@fortawesome/react-fontawesome": "0.0.17",
    "@lingui/react": "^2.0.2",
    "antd": "^3.2.1",
    "compression": "^1.7.2",
    "env2": "^2.2.0",
    "express": "^4.16.2",
    "joi-browser": "^13.0.1",
    "jszip": "^3.1.5",
    "lodash": "^4.17.5",
    "mjml": "^3.3.5",
    "moment": "^2.20.1",
    "mongodb": "^3.0.2",
    "nodemailer": "^4.4.2",
    "papaparse": "^4.3.7",
    "parse": "^1.11.0",
    "parse-dashboard": "^1.1.2",
    "parse-server": "^2.7.2",
    "prerender": "^5.2.1",
    "prerender-memory-cache": "^1.0.1",
    "prerender-node": "^2.7.4",
    "prop-types": "^15.6.0",
    "query-string": "^5.1.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-helmet": "^5.2.0",
    "react-redux": "^5.0.7",
    "react-redux-loading-bar": "^3.1.1",
    "react-router-dom": "^4.2.2",
    "react-sortable-hoc": "^0.6.8",
    "react-virtualized": "^9.18.5",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "tachyons": "^4.9.1",
    "webpack-assets-manifest": "^1.0.0"
  },
  "lingui": {
    "format": "minimal",
    "sourceLocale": "es",
    "srcPathDirs": [
      "./src/client"
    ],
    "localeDir": "./assets/locale"
  }
}

```

I also had problems getting lingui cli to run as stated in this [bug](https://github.com/lingui/js-lingui/issues/162), that I solved by installing `babel-runtime` and `babel-core`, I'm not sure why if in the dependencies of js-lingui/cli you have ["@babel/core": "^7.0.0-beta.38"](https://github.com/lingui/js-lingui/blob/master/packages/cli/package.json#L38), so I'm guessing the npm package is outdated?

**Comment by tricoder42** [comment]
@elios264 Thank you for detailed traceback, I'll take a look asap (latest this thursday).

There's a bug in `@lingui/cli` package, the dependencies in js files are wrong.

**Comment by tricoder42** [comment]
@elios264 `@lingui/cli` is fixed in **2.0.3**

**Comment by elios264** [comment]
Hi @tricoder42 

I think you rushed a little bit on publishing a new version, it is still failling in [here](https://github.com/lingui/js-lingui/blob/master/packages/cli/src/api/compile.js#L2) and [here](https://github.com/lingui/js-lingui/blob/master/packages/cli/src/api/compile.js#L5);

![capture](https://user-images.githubusercontent.com/15863852/36447149-1a21e4fa-1649-11e8-8721-cd2087452b49.PNG)

**Comment by tricoder42** [comment]
@elios264 Bummer. I fixed @lingui/cli and both presets in **v2.0.4**. Still I'm not sure what causes TypeError with options.loose.

**Comment by elios264** [comment]
Hey @tricoder42 

I installed and verified it is working now in **v2.0.4**. and the preset as well,
I think the TypeError with options.loose was happening due to mixing old `babel-*` deps with `@babel/*` deps, but since is that is fixed, options.loose error is gone as well.

Thank you! 

I also have other question that I'm not sure where to ask;

in the docs you say:

> Once we have all catalogs ready and translated, we can compile the JSON into a minified JS file with the compile command. This command parses the messages in MessageFormat and compiles them into simple functions. It also adds plural rules to a production ready catalog

**Why not reference `messages.json`  instead of `messages.js`?**,  I'm referencing them directly using webpack so in production mode they will get minified, I get it for dynamic loading but otherwise I'm not sure, does it have something to do with?

>  It also adds plural rules to a production ready catalog

I haven't use plurals yet, so I haven't seen how they are stored in messages.json.

**Comment by tricoder42** [comment]
In production you need alway reference `messages.js` (compiled catalog). There's a webpack loader to make things easier, which allows you to reference `messages.json` and the file is compiled to `messages.js` on-the-fly.

This is not only about language data (e.g. plurals). In production, the message parser isn't available (because it's slow and large) and compiled catalog contains messages compiled to functions.

**Comment by elios264** [comment]
Great, I'm using the loader now. 
Thanks!.

**Comment by ripern** [comment]
> In production you need alway reference `messages.js` (compiled catalog). There's a webpack loader to make things easier, which allows you to reference `messages.json` and the file is compiled to `messages.js` on-the-fly.
> 
> This is not only about language data (e.g. plurals). In production, the message parser isn't available (because it's slow and large) and compiled catalog contains messages compiled to functions.

@tricoder42 I might be misunderstanding something but why do you first state that in production you need to reference messages.js and then in the sentence after mention that there is a webpack loader which allows you to NOT have to reference messages.js directly?  I have used the latter way in dev but had problems with it in production, so just looking for an answer to if the dynamic loading should be used in production or not.

Cheers
