### ISSUE TITLE
Incorrect parsing locale string

### ISSUE THREAD

**Issue by lexkrstn** [lingui/js-lingui#164]
It seems like the function `loadLanguageData` from `@lingui/core/cjs` can only deal with only underscore sign being used as the locale separator. But when it comes to strings looking like `en-US` it fails to split them.

**Comment by adamgruber** [comment]
It appears that jsLingui used to support `en-US` but that was changed to `en_US` as part of https://github.com/lingui/js-lingui/pull/66. The problem is that `en_US` is not considered a valid language tag for things like `Intl.DateTimeFormat`.
```js
new Intl.DateTimeFormat('en-US') // DateTimeFormat {}
new Intl.DateTimeFormat('en_US') // Uncaught: RangeError: Invalid language tag: en_US
```
I would expect a library like this to either support both `-` and `_` but normalize it under the hood or to only allow valid language tags.

**Comment by adamgruber** [comment]
@tricoder42 Looks like this was fixed [here](https://github.com/lingui/js-lingui/commit/fe8f268234c1165962f485b1204bb2f5cbd44f81) and is part of 2.0.6. Any chance you could publish the latest version?

**Comment by tricoder42** [comment]
@adamgruber Hey, I've just release **2.0.7** which includes this fix. Let me know if problem persists. Thanks you!

**Comment by adamgruber** [comment]
@tricoder42 I'm still having an issue with the CLI where I cannot add `en-US` as my locale. I opened a separate issue for it. https://github.com/lingui/js-lingui/issues/207
