### ISSUE TITLE
Newline ignored when used in the <Trans> component (React Native)

### ISSUE THREAD

**Issue by jeanregisser** [lingui/js-lingui#324]
**Describe the bug**
When using a newline character within the `<Trans>` component, it gets ignored.

**To Reproduce**

```jsx
import { Text } from 'react-native';
import { Trans } from '@lingui/react';

export default function App() {
  return (
    <Text>
      <Trans id="howItWorks">
        1. You get two free weeks of unlimited access.{'\n'}
        2. Choose your plan.
      </Trans>
    </Text>
  );
}
```

Result:

![img_1163](https://user-images.githubusercontent.com/57791/45419460-afbc6600-b687-11e8-939b-aee03f90b5eb.PNG)

**Expected behavior**
It should render it respecting the newline.

Note that if I remove the `<Trans>` component it gets rendered properly:

![img_1161](https://user-images.githubusercontent.com/57791/45419488-c1057280-b687-11e8-8ebf-68145c533f5f.PNG)

**Additional context**

- jsLingui version `2.7.0`
- Babel version 
```text
$ npm list babel-core
├─┬ jest@22.4.3
│ └─┬ jest-cli@22.4.3
│   └─┬ jest-runtime@22.4.3
│     └── babel-core@6.26.0  deduped
└─┬ react-native@0.55.3
  ├── babel-core@6.26.0
  ├─┬ babel-register@6.26.0
  │ └── babel-core@6.26.0  deduped
  ├─┬ fbjs-scripts@0.8.3
  │ └── babel-core@6.26.0  deduped
  └─┬ metro@0.30.2
    └── babel-core@6.26.0  deduped
```
- Your Babel config (e.g. `.babelrc`)

```text
module.exports = {
  presets: ['react-native', '@lingui/babel-preset-react'],
  plugins: [['module-resolver', { root: ['./src'] }]],
};
```

- React Native version `0.55.3`

**Comment by tricoder42** [comment]
Hey @jeanregisser, this is bummer. Newlines and whitespaces are normalized (leading/trailing whitespace + newline are replaced with single space) so the localized message contains only significant characters. I didn't know that react-native treats newlines differently.

I'll think what we can do about it. It seems that newlines are removed from JSX by default and you have to force it using `{'\n'}`? How this would render?

```jsx
import { Text } from 'react-native';
import { Trans } from '@lingui/react';

export default function App() {
  return (
    <Text>
        1. You get two free weeks of unlimited access.
        2. Choose your plan.
    </Text>
  );
}
```

On single line or two?

---

Meanwhile, you have to separate messages like this:

```jsx
import { Text } from 'react-native';
import { Trans } from '@lingui/react';

export default function App() {
  return (
    <Text>
      <Trans id="howItWorks1">
        1. You get two free weeks of unlimited access.
      </Trans>{'\n'}
      <Trans id="howItWorks2">
        2. Choose your plan.
      </Trans>
    </Text>
  );
}
```

**Comment by jeanregisser** [comment]
Your first example (without explicit `{'\n'}`) renders on a single line.

Thanks for the workaround until you find a solution for React Native.

**Comment by FredyC** [comment]
What about like this, would that works also? Could be easier to read, but in regards of translation, it might be better to have both phrases separately.

```js
import { Text } from 'react-native';
import { Trans } from '@lingui/react';

export default function App() {
  return (
    <Trans id="howItWorks">
      <Text>1. You get two free weeks of unlimited access.</Text>
      <Text>2. Choose your plan.</Text>
    </Trans>
  );
}
```

**Comment by tricoder42** [comment]
I wouldn't place `Text` inside `Trans` component... That would create unnecessary tags inside message.

Maybe this one if `Text` is added as `defaultRender` to `I18nProvider`:

```js
import { Text } from 'react-native';
import { Trans } from '@lingui/react';

export default function App() {
  return (
    <React.Fragment>
      <Trans id="howItWorks1">1. You get two free weeks of unlimited access.</Trans>
      <Trans id="howItWorks2">2. Choose your plan.</Trans>
    </React.Fragment>
  );
}
```

But still: We should keep newlines which are forced by users and only remove *implicit* newlines.

**Comment by tricoder42** [comment]
Fixed and waiting for v3 release.

**Comment by normanzb** [comment]
We are still experiencing this with below versions:

```json
{
"@lingui/core": "^3.10.2",
"@lingui/react": "^3.9.0",
"@lingui/macro": "^3.9.0"
}
```

Is it a regression issue?
