### ISSUE TITLE
Cannot read property 'locale' of null for `@lingui/loader`

### ISSUE THREAD

**Issue by FredyC** [lingui/js-lingui#642]
**Describe the bug**
App crashes when using `@lingui/loader`

**To Reproduce**
Install deps and run example of `create-react-app` from `next` branch.

**Expected behavior**
It should work :)

**Additional context**
![image](https://user-images.githubusercontent.com/1096340/79052362-4e2ef580-7c36-11ea-9e14-d9bd15691e4d.png)

It's coming from this line. Apparently the `getCatalogForFile` returns `null` for some reason. I will investigate it further, but I suspect it's a classic issue of wrong path separators (I am on Windows).

https://github.com/lingui/js-lingui/blob/24d521ff385647f69f73188fd35e07079efdc1f3/packages/loader/src/index.js#L41

- jsLingui version ``lingui --version``: 3.0.0-10

**Comment by tricoder42** [comment]
Unfortunatelly I can't test it on Windows. Let me know what you've found 👍

**Comment by FredyC** [comment]
So it seems the `minimatch` is a culprit here. Looking at the `getCatalogForFile` when I have `src\locales\{locale}.po` in input the resulting regexp is `/^(?:src\/locales\/([^\/.]+)\.po)$/` expecting wrong separator and then match fails because webpack provides file name with backward slash as well.

https://github.com/lingui/js-lingui/blob/24d521ff385647f69f73188fd35e07079efdc1f3/packages/cli/src/api/catalog.ts#L390

There is even a [long-standing PR in minimatch](https://github.com/isaacs/minimatch/pull/103) that probably fixes it along with linked open issues.

I also found `path.normalize()` in NodeJS which would fix separators in the path, but with `minimatch` issues it's a lost cause.

It's rather silly that even in 2020 we are still unable to solve this stupid problem in some universal way. I am not that well oriented in NodeJS-verse so I am not sure what are alternatives to `minimatch`.

**Comment by FredyC** [comment]
I have found [micromatch](https://www.npmjs.com/package/micromatch) which seems to be the successor that actually works.

And now I am freaking out because snapshot testing is a huge problem here. All tests are failing for me because of wrong path separators in snapshots :/

**Comment by tricoder42** [comment]
If you know that the snapshots are correct, just accept them and yolo. I’ve checked appveyor which runs tests on windows and the tests pass there. Feel free to push even unfinished pr, I’m gonna check it in the morning. Cheers 👍

**Comment by FredyC** [comment]
Fixed in #643

**Comment by panuhorsmalahti** [comment]
I still get this issue with 3.0.0-11. I checked that _getCatalogForFile is null for me (on Windows).

**Comment by FredyC** [comment]
@panuhorsmalahti Can you try some reproduction repo? It works fine for me (also on Windows). Perhaps you have found a different edge case there.

**Comment by panuhorsmalahti** [comment]
Yeah, it seems to be a different issue. The catalog glob in the function is a different path from the file:
catalogGlob: locale/*/messages.po
file: src\locales\en\messages.po

And the catalog location for me seems to be default: https://github.com/lingui/js-lingui/blob/next/packages/conf/src/index.ts#L43
I'll try changing that, sec.

**Comment by MartijnHols** [comment]
It doesn't work if you use `<rootDir>` in your catalog path.

**Comment by semoal** [comment]
> It doesn't work if you use `<rootDir>` in your catalog path.

Hm with latest versión, should work properly with rootdir, create a new issue if you find this not working properly

**Comment by MartijnHols** [comment]
Yes on latest version. It's an easy test too if you're using @lingui/loader; just prepend your catalog paths with `<rootDir>/`.

**Comment by semoal** [comment]
> Yes on latest version. It's an easy test too if you're using @lingui/loader; just prepend your catalog paths with `<rootDir>/`.

Alright, I'll take a look then

**Comment by semoal** [comment]
> Yes on latest version. It's an easy test too if you're using @lingui/loader; just prepend your catalog paths with `<rootDir>/`.

Martijn could you tell me the differences to see the error in our example of create-react-app?
https://github.com/lingui/js-lingui/tree/main/examples/create-react-app

We are using <rootDir> in catalog paths, and @lingui/loader in `i18n.ts` and works as expected. Probably i'm missing something =)

**Comment by morel6c** [comment]
@semoal @tricoder42 

The project with React (examples) does not work. Here is the error in screenshot. Tested on January 30, 2021. The Lingui project has a lot of bugs, to this day even with version 3.4.0, extraction does not work well, compilation does not work well either, production interpolation always returns the name of the variable {var} and the loader (@lingui/loader) returns "TypeError: Cannot read property 'locale' of null". In development mode, the interpolation works well, but when going to production nothing works as expected. There have been many problems related to these contexts, I've gone through the issues a bit but so far (Jan 30, 2021) none of this is fixed. Since I installed Lingui, I have only problems and it's a shame not to be able to install it and work without too many complications. 

![screenshot-localhost-3000-1612041743343](https://user-images.githubusercontent.com/26247346/106368717-0d7ea500-634c-11eb-983a-6e21ca21674f.png)

**Comment by semoal** [comment]
> @semoal @tricoder42
> 
> The project with React [https://github.com/lingui/js-lingui/tree/main/examples/create-react-app](https://github.com/lingui/js-lingui/tree/main/examples/create-react-app?rgh-link-date=2021-01-30T21%3A40%3A06Z) (examples) does not work. Here is the error in screenshot. Tested on January 30, 2021. The Lingui project has a lot of bugs, to this day even with version 3.4.0, extraction does not work well, compilation does not work well either, production interpolation always returns the name of the variable {var} and the loader (@lingui/loader) returns "TypeError: Cannot read property 'locale' of null". In development mode, the interpolation works well, but when going to production nothing works as expected. There have been many problems related to these contexts, I've gone through the issues a bit but so far (Jan 30, 2021) none of this is fixed. Since I installed Lingui, I have only problems and it's a shame not to be able to install it and work without too many complications.
> 
> ![screenshot-localhost-3000-1612041743343](https://user-images.githubusercontent.com/26247346/106368717-0d7ea500-634c-11eb-983a-6e21ca21674f.png)

Haha :) I'll conclude with your super useful commentary about Lingui... That Lingui with 150.000 DOWNLOADS MONTHLY, used by the biggest companies and maintained and created for FREE, probably "LINGUI PROBLEMS" are just your problems. Don't be a shame for the community and do something useful for it.

Thanks 👍🏻

**Comment by msixc** [comment]
Does it make sense that it works in some people and not in others? My intention was not to shock you, I'm part of the community myself but just to make you understand that the project works in some people and not in others and it's not normal. If you need a specific configuration, you have to mark it somewhere. For the create-react-app project, I followed the README "yarn install - yarn start" and the page to display this error. Try the version in the "examples" folder.

**Comment by semoal** [comment]
> Does it make sense that it works in some people and not in others? My intention was not to shock you, I'm part of the community myself but just to make you understand that the project works in some people and not in others and it's not normal. If you need a specific configuration, you have to mark it somewhere. For the create-react-app project, I followed the README "yarn install - yarn start" and the page to display this error. Try the version in the "examples" folder.

A lot of projects work for some people and not for others, its normal because programs are made by humans that makes mistakes. 

We try to keep Lingui as much as maintained as we can, practically we release a new version each tuesday. 

Sincerely i would like to all projects being as good maintained as Lingui is.

About your issue, I think in the next version is fixed(Next tuesday), because we did a minor change to resolve catalogs for snowpack plugin and Will resolve the issue Also for webpack

**Comment by msixc** [comment]
> That Lingui with 150.000 DOWNLOADS MONTHLY, used by the biggest companies
@semoal Yes you didn't lie but the heart of lingui if I may say so, is the extraction (yarn extract) and compilation (yarn compile - prod). It's different actions must be universal for all users, if a yarn extract works for one user and not for another it's not the same dependency. It was just constructive criticism to get the team to look at the problems and fixes. It's still used by big companies as you say. Peace!

**Comment by lgenzelis** [comment]
Hi folks! :) I see that the issue is closed, but I'm observing the exact same behavior reported by @msixc . To reproduce it:
```
git clone git@github.com:lingui/js-lingui.git
cd js-lingui/examples/create-react-app/
yarn install
yarn start
```

<img width="1050" alt="Screen Shot 2021-02-11 at 9 22 27 PM" src="https://user-images.githubusercontent.com/4582440/107716028-405f5c00-6caf-11eb-80dd-8b803a583fdd.png">

(my `yarn` version is 1.22.10, just in case)

Am I missing some step?

**Comment by lgenzelis** [comment]
I open a new [issue](https://github.com/lingui/js-lingui/issues/976), since this one is closed.
