### ISSUE TITLE
Cannot process file /<path>.tsx: Duplicate declaration "Trans"

### ISSUE THREAD

**Issue by ericvera** [lingui/js-lingui#952]
**Describe the bug**
When running `lingui extract` I get the error `Duplicate declaration "Trans"` ("t" seems to be OK).

**To Reproduce**

```
Cannot process file /<path>.tsx: Duplicate declaration "Trans"
  15 | // i18n
  16 | import { useI18N, Locale } from 'i18n';
> 17 | import { t, Trans } from '@lingui/macro';
```

**Expected behavior**
No error on `lingui extract`

**Additional context**
- Tried v3.4.0 and still had issues
- CLI version v3.2.1 repros the issue
- CLI version v3.1.0 does not repro the issue
- @babel/core@7.12.10 
- Using Lingui in a NextJS project
- Looked at the diff (https://github.com/lingui/js-lingui/compare/v3.1.0...v3.2.1) and there are two changes that jump out, but I don't understand the code enough to troubleshoot part this point. (https://github.com/lingui/js-lingui/pull/846 and https://github.com/lingui/js-lingui/pull/854) (cc @semoal and @Bertg in case they have any ideas)
- .babelrc
````
{
  "presets": ["next/babel"],
  "plugins": ["macros"],
  "env": {
    "test": {
      "plugins": ["dynamic-import-node"]
    }
  }
}
````

**Comment by semoal** [comment]
Hi Eric! Thanks for using Lingui
Are you using plain lingui extract or are you passing NODE_ENV=production

**Comment by ericvera** [comment]
> Hi Eric! Thanks for using Lingui
> Are you using plain lingui extract or are you passing NODE_ENV=production

I was using `lingui extract` with the `--overwrite` option, but also tried with without that option (same result). No NODE_ENV set. Also tried echo before the command to make sure it is not set.

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/issues/433 We have here a similar issue here, let me create a sample repo (or if you could provide us a sample repo for reproducing the issue, I could check in detail tomorrow) :)

**Comment by semoal** [comment]
https://codesandbox.io/s/nextjs-lingui-djzqm?file=/pages/index.tsx Here is a codesandbox that you could modify with your changes :)

**Comment by ericvera** [comment]
I just set the NODE_ENV=test and it seems to work. I was not setting NODE_ENV=production, but I guess that would be the default?

**Comment by semoal** [comment]
> I just set the NODE_ENV=test and it seems to work. I was not setting NODE_ENV=production, but I guess that would be the default?

Probably in some process is setting up NODE_ENV=production, or the ci.. Dunno 
Is not a directly issue with lingui, this is because lingui uses source code trough AST to explore what needs to extract, so if the code is generated via NODE_ENV=production babel applies other algorithm and brokes lingui.

Anyways I'll take a look to our internal babel generator if we can force this to be in NODE_ENV=development for example..

**Comment by ericvera** [comment]
Sounds good. For some more info...

I used `yarn repro` with the below `package.json` definition and it works. `a.js` just contains `console.log(process.env.NODE_ENV)` which prints out `undefined`. 

````
"scripts": {
   "repro" : "cross-env NODE_ENV=development lingui extract && node a.js"
   ...
}
````

**Comment by fhuszti** [comment]
Thanks guys, changing `"extract": "lingui extract"` to `"extract": "NODE_ENV=development lingui extract"` fixed the problem on my fresh install with NextJS. 
If I understood correctly what is said [here](https://github.com/lingui/js-lingui/issues/433#issuecomment-454678661) I can keep it like that and not worry about it because it doesn't need to have `NODE_ENV=production` when building for prod?

**Comment by semoal** [comment]
Exactly, basically node_env=production applies changes to code that lingui can't interpret

**Comment by semoal** [comment]
I think i got a fix for this "issue", babel transform api allows to overwrite NODE_ENV variable internally, so probably won't be required to use nODE_ENV=development before lingui extract command.

@ericvera next tuesday we'll release a new version with this change introduced if you can tell us if this fixes the issue, would be amazing =)

**Comment by ericvera** [comment]
Happy to.

**Comment by semoal** [comment]
@ericvera Released 3.5.0 give it a try plz

**Comment by SleepWalker** [comment]
The error is still there. It still does not work without `NODE_ENV=development `

**Comment by semoal** [comment]
Alright i'll take a deeper look, tough that forcing babel to use development was enough, but looks that NODE_ENV always has precedence. 

If any of you has a reproduction repo where i can try will be super

**Comment by SleepWalker** [comment]
I'll try to debug it a little bit. Looks like the error happens somewhere after [transformFileSync](https://github.com/lingui/js-lingui/commit/f368b353e975dab4024b755eb9d70f48b535a693#diff-20e9e7ece9d8ad2716019366457a9022f80aafff627a1f9201dc10ec1fd22a70R27) call. I have commented out that call and the error is still there.

**Comment by SleepWalker** [comment]
In my case the solution is to pass `babelrc: false` in the options here:

https://github.com/lingui/js-lingui/blob/main/packages/cli/src/api/extractors/typescript.ts#L50-L55

Here is babelrc from my project:

```json
{
  "presets": [
    [
      "next/babel",
      {
        "preset-react": {
          "runtime": "automatic",
          "importSource": "@emotion/react"
        }
      }
    ]
  ],
  "plugins": ["@emotion/babel-plugin", "macros"]
}
```

The conflicting part is inside `babel-plugin-transform-react-remove-prop-types` which is enabled by `next/babel` in isProduction mode (detected from `process.env`:

https://github.com/vercel/next.js/blob/canary/packages/next/build/babel/preset.ts

If `babel-plugin-transform-react-remove-prop-types` is configured with `{ removeImport: true }` (removes prop-types imports from code base), it will break the extract process. The error happens because of this line:

https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/d3a618a9c72be08485f5e20659c917b300cf7b74/src/index.js#L364

I don't know what `scope.crawl` does under the hood.

Looks like my issue is not due to the bug inside lingui :sweat_smile:. I'll continue to use `NODE_ENV=development`

**Comment by ericvera** [comment]
> @ericvera Released 3.5.0 give it a try plz

Same as @SleepWalker. Also still seeing the issue with the latest version.

**Comment by armandabric** [comment]
After upgrading from v3.2.3 to v3.6.0 I encounter the same error. Forcing the NODE_ENV to development fix the issue.

**Comment by Manubi** [comment]
Just wanted to let you know, I just switched to lingui and the fix was the node enviornment.
`yarn run NODE_ENV=development lingui extract --clean && lingui compile`

**Comment by Anonymous-dev-v** [comment]
The error is still there. `Duplicate` declaration "Trans"`

**Comment by gemcloud** [comment]
I fixed the issue on my nextjs project on windows 10, windows 11!!!
Points are: 1 & 2
  **1. First of all you must install "npm i cross-env" on windows system (windows 10, 11).**
  **2. You have to use "NODE_ENV=development" command** 
         **Notice: cross-env NODE_ENV=development! cross-env NODE_ENV=development!! cross-env NODE_ENV=development!!!**
  use below command on "package.json"
  ```
      "lang:extract": "cross-env NODE_ENV=development lingui extract --clean",
  ```
  3. run "> yarn lang:extract" on console. each  "messages.po" file created!
  4. installed package version as below
     "@lingui/react": "^3.13.0",
     "@lingui/cli": "^3.13.0",
     "@lingui/loader": "^3.13.0",
     "@lingui/macro": "^3.13.0",

Hopeful help!

**Comment by MarkMurphy** [comment]
I think this should probably be re-opened. This is still an issue today with the latest version of lingui, as of writing that's 3.13.2

**Comment by semoal** [comment]
Will try to take a deeper look if we can resolve this somehow internally in the Lingui CLI

**Comment by OssiPesonen** [comment]
> I fixed the issue on my nextjs project on windows 10, windows 11!!! Points are: 1 & 2 **1. First of all you must install "npm i cross-env" on windows system (windows 10, 11).** **2. You have to use "NODE_ENV=development" command** **Notice: cross-env NODE_ENV=development! cross-env NODE_ENV=development!! cross-env NODE_ENV=development!!!** use below command on "package.json"
> 
> ```
>     "lang:extract": "cross-env NODE_ENV=development lingui extract --clean",
> ```
> 
> 3. run "> yarn lang:extract" on console. each  "messages.po" file created!
> 4. installed package version as below
>    "@lingui/react": "^3.13.0",
>    "@lingui/cli": "^3.13.0",
>    "@lingui/loader": "^3.13.0",
>    "@lingui/macro": "^3.13.0",
> 
> Hopeful help!

I managed to get around this issue using @gemcloud's comment. However, cross-env is for Windows users mostly and I work both on OS X and Windows, so I had to create a separate command for my Windows extracts. Not a big deal, but this issue still exists with Next.js 12.1.0 and @lingui/cli 3.13.2, @lingui/macro 3.12.1 and @lingui/react 3.13.2. Added Lingui to my project today, in fact.

**Comment by armandabric** [comment]
This is still a thing

**Comment by 2snEM6** [comment]
This is still happening to me in the latest version. I think this is not fixed

**Comment by NitrousBGC** [comment]
> I fixed the issue on my nextjs project on windows 10, windows 11!!! Points are: 1 & 2 **1. First of all you must install "npm i cross-env" on windows system (windows 10, 11).** **2. You have to use "NODE_ENV=development" command** **Notice: cross-env NODE_ENV=development! cross-env NODE_ENV=development!! cross-env NODE_ENV=development!!!** use below command on "package.json"
> 
> ```
>     "lang:extract": "cross-env NODE_ENV=development lingui extract --clean",
> ```
> 
> 3. run "> yarn lang:extract" on console. each  "messages.po" file created!
> 4. installed package version as below
>    "@lingui/react": "^3.13.0",
>    "@lingui/cli": "^3.13.0",
>    "@lingui/loader": "^3.13.0",
>    "@lingui/macro": "^3.13.0",
> 
> Hopeful help!

This did the trick for me ! Thank you!

**Comment by mohanads** [comment]
I ran into this and the `NODE_ENV=development` didn't help.
However, I was using the `@babel/env` and `@babel/react` presets. After removing `@babel/env` and changing `@babel/react` to `@babel/preset-react`, the error no longer appeared after running `lingui extract`.

**Comment by Strnadj** [comment]
I ran into this again, `@babel/preset-env` is not a part of my .babelrc... in case I remove it completely, lingui starts to complain.

**Comment by ianchanning** [comment]
I'm too using Next.js and I've been using the `NODE_ENV=development` fix for quite a while, but today for some reason or another I started getting the same errors:

```
Cannot process file /src/components/hooks/useNotifications.js: Duplicate declaration "Trans"
  1 | import React, { useEffect, useState, useContext, useRef } from 'react'
> 2 | import { Trans } from '@lingui/macro'
    |          ^^^^^
```

I was using lingui 3.12.1 but I updated to the current latest 3.14.0.

I noticed that without using `NODE_ENV=development` all files gave errors, but with using it about only 9 files gave errors. For these ones I replaced `<Trans>` macro with `i18n` from `useLingui()` and the `t` macro instead.

```
i18n._(t`...`)
```
These fixed my errors one by one.

**Comment by athammer** [comment]
Also using next.js.

I tried downgrading all the way to 3.0 with no luck. I'm currently on 3.14.0. I also had to use the t macro function sadly. I'll keep digging to see if I can find the route of the issue.

**Comment by capaj** [comment]
This `lingui:extract": "NODE_ENV=development lingui extract` should really get documented as all the people who use next.js will have to set this for the extraction to work properly.

**Comment by athammer** [comment]
Possible solution [here](https://github.com/lingui/js-lingui/issues/433#issuecomment-1218041477)?

Not sure what exactly the fix for the library is but hopefully this can point someone in the right direction to fix this. I'm guessing this is impacting pretty much everyone trying to use this library right now.

**Comment by thekip** [comment]
Looks like its still an issue. I reopen this and assign for myself.

**Comment by thekip** [comment]
Fixed in https://github.com/lingui/js-lingui/pull/1367 would be released as part of v4
